name: BarrelsTerminal
version: 2.101
main: com.gmail.nudoing.spigot.barrelsterminal.BarrelsTerminal
api-version: 1.13
author: Nudon
website: https://www.youtube.com/user/nudoing/

commands:
  BTHelp:
    description: BarrelTerminal help

